using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Oathlord.Shared.Economy.Components;
using Content.Oathlord.Shared.Economy.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class EconomyLoanWindow : FancyWindow
{
    private OathlordEconomySystem _economy;

    private Entity<EconomyAccountComponent> _account;

    public Action<LoanData>? GrantLoanRequest;
    public Action<LoanData>? PayLoanRequest;

    public EconomyLoanWindow(
        OathlordEconomySystem econ,
        Entity<EconomyAccountComponent>? account)
    {
        RobustXamlLoader.Load(this);
        _economy = econ;

        if (account is not { } econAccount)
            return;

        _account = econAccount;
        AddLoanButton.OnPressed += AddLoanButtonOnOnPressed;

        Populate();
    }

    private void AddLoanButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        // todo: this is for testing
        var loanData = new LoanData();
        loanData.Amount = 200;
        loanData.DueTime = TimeSpan.FromMinutes(5);
        loanData.Reason = "This is a test reason!";

        GrantLoanRequest?.Invoke(loanData);
    }

    public void Populate()
    {
        Loans.Children.Clear();
        var loans = _economy.GetLoans(_account.AsNullable());
        if (loans is not { } loanIterator || !loans.Any())
            return;

        foreach (var loan in loanIterator)
        {
            var loanControl = new LoanControl(loan, _economy.GetLoanInterest(_account));
            loanControl.PayLoanRequest += data =>
            {
                PayLoanRequest?.Invoke(data);
            };

            Loans.AddChild(loanControl);
        }
    }
}

