using Content.Client.UserInterface.Controls;
using Content.Oathlord.Shared.Economy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Economy.UI;

/// <summary>
/// Window that gives you the ability to add a loan to an account
/// Relies on <see cref="EconomyLoanWindow"/>
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class EconomyGrantLoanWindow : FancyWindow
{
    public Action<LoanData>? GrantLoanRequest;

    public EconomyGrantLoanWindow()
    {
        RobustXamlLoader.Load(this);

        ConfirmLoanButton.OnPressed += ConfirmLoanButtonOnOnPressed;
    }

    private void ConfirmLoanButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        if (!int.TryParse(AmountLoanEdit.Text, out var amount) || amount <= 0)
            return;

        if (!float.TryParse(DueTimeLoanEdit.Text, out var timeSpan) || timeSpan <= 0)
            return;

        var loanData = new LoanData
        {
            Amount = amount,
            DueTime = TimeSpan.FromMinutes(timeSpan),
            Reason = ReasonLoanEdit.Text,
        };

        GrantLoanRequest?.Invoke(loanData);
        Close();
    }
}

