using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Economy.UI;

// TODO: This should support withdrawing different kinds of nar
[GenerateTypedNameReferences]
public sealed partial class EconomyWithdrawWindow : FancyWindow
{
    public Action<int>? AmountWithdrawn;

    public EconomyWithdrawWindow()
    {
        RobustXamlLoader.Load(this);

        WithdrawAmount.OnTextChanged += DepositAmountOnOnTextChanged;
        ConfirmButton.OnPressed += ConfirmButtonOnOnPressed;
    }

    private void DepositAmountOnOnTextChanged(LineEdit.LineEditEventArgs obj)
    {
        if (!int.TryParse(obj.Text, out var amount) || amount <= 0)
        {
            ConfirmButton.Disabled = true;
            return;
        }

        ConfirmButton.Disabled = false;
    }

    private void ConfirmButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        if (!int.TryParse(WithdrawAmount.Text, out var amount) || amount <= 0)
            return;

        AmountWithdrawn?.Invoke(amount);
        Close();
    }
}

