using Content.Client.UserInterface.Controls;
using Content.Oathlord.Shared.Economy.Components;
using Content.Oathlord.Shared.Economy.Systems;
using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class EconomyMachineWindow : FancyWindow
{
    [Dependency] private IEntityManager _entMan = default!;

    public Action<NetEntity?, int>? RequestDeposit;
    public Action<NetEntity?, int>? RequestWithdraw;

    private EconomyDepositWindow? _depositWindow;
    private EconomyWithdrawWindow? _withdrawWindow;

    private OathlordEconomySystem? _economy;
    private EntityUid? _owner;
    private Entity<EconomyAccountComponent>? _selectedAccount;

    private readonly EntityQuery<EconomyAccountComponent> _accountQuery;

    public EconomyMachineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _accountQuery = _entMan.GetEntityQuery<EconomyAccountComponent>();

        _economy = _entMan.System<OathlordEconomySystem>();

        WithdrawButton.OnPressed += WithdrawButtonOnOnPressed;
        DepositButton.OnPressed += DepositButtonPressed;
    }

    public override void Close()
    {
        base.Close();

        CloseOtherWindows();

        WithdrawButton.OnPressed -= WithdrawButtonOnOnPressed;
        DepositButton.OnPressed -= DepositButtonPressed;
    }

    public void Populate()
    {
        Accounts.Children.Clear();
        if (_economy is null || _owner is not { } owner)
            return;

        if (_economy.GetCurrentEconomy(owner) is not { } mapEconomy)
            return;

        foreach (var account in mapEconomy.Comp.ActiveAccounts)
        {
            var name = Identity.Name(account, _entMan);
            var btn = new Button
            {
                Text = name,
            };
            Accounts.AddChild(btn);

            btn.OnPressed += args => BtnOnOnPressed(args, account, name);
        }
    }

    private void BtnOnOnPressed(BaseButton.ButtonEventArgs _, EntityUid account, string accountName)
    {
        if (!_accountQuery.TryComp(account, out var econ))
            return;

        CloseOtherWindows();

        _selectedAccount = (account, econ);
        SetupAccount(_selectedAccount.Value, accountName);

        SelectInfo.Visible = false;
    }

    private void DepositButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        _depositWindow?.Close();

        _depositWindow = new EconomyDepositWindow();
        _depositWindow.OnClose += () => _depositWindow = null;
        _depositWindow.AmountDeposited += args =>
        {
            if (_selectedAccount is not { } selectedAccount)
                return;

            RequestDeposit?.Invoke(_entMan.GetNetEntity(selectedAccount.Owner), args);
        };

        _depositWindow.OpenCentered();
    }

    private void WithdrawButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        _withdrawWindow?.Close();

        _withdrawWindow = new EconomyWithdrawWindow();
        _withdrawWindow.OnClose += () => _withdrawWindow = null;
        _withdrawWindow.AmountWithdrawn += args =>
        {
            if (_selectedAccount is not { } selectedAccount)
                return;

            RequestWithdraw?.Invoke(_entMan.GetNetEntity(selectedAccount.Owner), args);
        };

        _withdrawWindow.OpenCentered();
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }

    /// <summary>
    /// Sets up anything related to the account
    /// </summary>
    private void SetupAccount(Entity<EconomyAccountComponent> ent, string name)
    {
        AccountName.Text = $"Name: {name}";
        AccountStored.Text = StoredText(ent.Comp.Stored);

        AccountInfo.Visible = true;
    }

    /// <summary>
    /// Updates any relevant info related to the current selected account (e.g. stored money)
    /// </summary>
    public void UpdateInfo()
    {
        if (_selectedAccount is not { } selectedAccount)
            return;

        AccountStored.Text = StoredText(selectedAccount.Comp.Stored);
    }

    /// <summary>
    /// Closes any other windows that were created by this window
    /// </summary>
    private void CloseOtherWindows()
    {
        _depositWindow?.Close();
        _withdrawWindow?.Close();
    }

    /// <summary>
    /// Returns a re-usable text for stored text, as we prefer to not use locstrings for our codebase
    /// </summary>
    private string StoredText(int stored)
    {
        return $"Stored: {stored}";
    }
}

