using Content.Client.UserInterface.Controls;
using Content.Oathlord.Shared.Economy.Prototypes;
using Content.Oathlord.Shared.Economy.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class EconomyTransactionWindow : FancyWindow
{
    private Dictionary<ProtoId<EconomyCurrencyPrototype>, int> _currencyAmounts = new();

    public Action<Dictionary<ProtoId<EconomyCurrencyPrototype>, int>>? TransactionConfirm;

    public EconomyTransactionWindow(
        OathlordEconomySystem economy,
        IPrototypeManager protoMan,
        EntityUid owner,
        string windowName,
        bool showValues = true)
    {
        RobustXamlLoader.Load(this);

        Title = windowName;
        ConfirmButton.OnPressed += ConfirmButtonOnOnPressed;

        if (economy.GetCurrentEconomy(owner) is not { } mapEconomy)
            return;

        foreach (var (cur, value) in mapEconomy.Comp.StoredCurrencies)
        {
            if (!protoMan.TryIndex(cur, out var currencyPrototype))
                continue;

            _currencyAmounts.Add(cur, 0);

            var lineEdit = new LineEdit
            {
                HorizontalExpand = true,
                Text = "0",
                Margin = new Thickness(16)
            };

            // As an example for why this exists, depositing does not care about how much money we have in the vault.
            // It only increases the stored "ownership" of that money. Players won't get confused this way. At least I hope so!
            // On the other hand, withdrawing cares, because we take physical money from the vault directly...
            var currencyValue = showValues ? $"{value} {currencyPrototype.Name}" : $"{currencyPrototype.Name}";
            var name = new Label
            {
                Text = currencyValue,
                HorizontalExpand = true,
                Margin = new Thickness(8)
            };

            CurrenciesNames.AddChild(name);
            Currencies.AddChild(lineEdit);

            lineEdit.OnTextChanged += args => DepositAmountOnOnTextChanged(args, cur);
        }
    }

    private void DepositAmountOnOnTextChanged(LineEdit.LineEditEventArgs obj, ProtoId<EconomyCurrencyPrototype> cur)
    {
        foreach (var child in Currencies.Children)
        {
            if (child is not LineEdit lineEdit)
                continue;

            if (!int.TryParse(lineEdit.Text, out var amount) || amount < 0)
            {
                ConfirmButton.Disabled = false;
                return;
            }
        }

        if (!int.TryParse(obj.Text, out var thisAmount) || thisAmount < 0)
            return;

        ConfirmButton.Disabled = false;
        if (!_currencyAmounts.ContainsKey(cur))
            return;

        _currencyAmounts[cur] = thisAmount;
    }

    private void ConfirmButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        foreach (var child in Currencies.Children)
        {
            if (child is not LineEdit lineEdit)
                continue;

            if (!int.TryParse(lineEdit.Text, out var amount) || amount < 0)
                return;
        }

        TransactionConfirm?.Invoke(_currencyAmounts);
        Close();
    }
}

