using Content.Client.UserInterface.Controls;
using Content.Oathlord.Shared.Economy.Components;
using Content.Oathlord.Shared.Economy.Prototypes;
using Content.Oathlord.Shared.Economy.Systems;
using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class EconomyMachineWindow : FancyWindow
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;
    private readonly OathlordEconomySystem _economy;

    public Action<NetEntity?, Dictionary<ProtoId<EconomyCurrencyPrototype>, int>, EconomyTransaction>? RequestTransaction;

    private EconomyTransactionWindow? _transactionWindow;

    private EntityUid _owner;
    private Entity<EconomyAccountComponent>? _selectedAccount;

    private readonly EntityQuery<EconomyAccountComponent> _accountQuery;

    public EconomyMachineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _accountQuery = _entMan.GetEntityQuery<EconomyAccountComponent>();

        _economy = _entMan.System<OathlordEconomySystem>();

        WithdrawButton.OnPressed += _ => OpenTransactionMenu(EconomyTransaction.Withdraw);
        DepositButton.OnPressed += _ => OpenTransactionMenu(EconomyTransaction.Deposit);
    }

    public override void Close()
    {
        base.Close();

        CloseOtherWindows();
    }

    public void Populate()
    {
        Accounts.Children.Clear();

        if (_economy.GetCurrentEconomy(_owner) is not { } mapEconomy)
            return;

        foreach (var account in mapEconomy.Comp.ActiveAccounts)
        {
            var name = Identity.Name(account, _entMan);
            var btn = new Button
            {
                Text = name,
            };
            Accounts.AddChild(btn);

            btn.OnPressed += args => BtnOnOnPressed(args, account, name);
        }
    }

    private void BtnOnOnPressed(BaseButton.ButtonEventArgs _, EntityUid account, string accountName)
    {
        if (!_accountQuery.TryComp(account, out var econ))
            return;

        CloseOtherWindows();

        _selectedAccount = (account, econ);
        SetupAccount(_selectedAccount.Value, accountName);

        SelectInfo.Visible = false;
    }

    private void OpenTransactionMenu(EconomyTransaction type)
    {
        _transactionWindow?.Close();

        _transactionWindow = new EconomyTransactionWindow(_economy, _protoMan, _owner, GetWindowName(type));
        _transactionWindow?.OnClose += () => _transactionWindow = null;
        _transactionWindow?.TransactionConfirm += currencies =>
        {
            if (_selectedAccount is not { } selectedAccount)
                return;

            RaiseTransaction(_entMan.GetNetEntity(selectedAccount.Owner), currencies, type);
        };

        _transactionWindow?.OpenCentered();
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }

    /// <summary>
    /// Sets up anything related to the account
    /// </summary>
    private void SetupAccount(Entity<EconomyAccountComponent> ent, string name)
    {
        AccountName.Text = $"Name: {name}";
        AccountStored.Text = StoredText(ent.Comp.Stored);

        AccountInfo.Visible = true;
    }

    /// <summary>
    /// Updates any relevant info related to the current selected account (e.g. stored money)
    /// </summary>
    public void UpdateInfo()
    {
        if (_selectedAccount is not { } selectedAccount)
            return;

        AccountStored.Text = StoredText(selectedAccount.Comp.Stored);
    }

    /// <summary>
    /// Closes any other windows that were created by this window
    /// </summary>
    private void CloseOtherWindows()
    {
        _transactionWindow?.Close();
    }

    /// <summary>
    /// Returns a re-usable text for stored text, as we prefer to not use locstrings for our codebase
    /// </summary>
    private string StoredText(int stored)
    {
        return $"Stored: {stored}";
    }

    /// <summary>
    /// Raises a <see cref="RequestTransaction"/> event
    /// </summary>
    private void RaiseTransaction(
        NetEntity entity,
        Dictionary<ProtoId<EconomyCurrencyPrototype>, int> currencies,
        EconomyTransaction type)
    {
        RequestTransaction?.Invoke(entity, currencies, type);
    }

    private string GetWindowName(EconomyTransaction type)
    {
        // todo: if we get more types, do switch statement...
        return type == EconomyTransaction.Deposit ? "Deposit" : "Withdraw";
    }
}

