using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class EconomyDepositWindow : FancyWindow
{
    public Action<int>? AmountDeposited;

    public EconomyDepositWindow()
    {
        RobustXamlLoader.Load(this);

        DepositAmount.OnTextChanged += DepositAmountOnOnTextChanged;
        ConfirmButton.OnPressed += ConfirmButtonOnOnPressed;
    }

    private void DepositAmountOnOnTextChanged(LineEdit.LineEditEventArgs obj)
    {
        if (!int.TryParse(DepositAmount.Text, out var amount) || amount <= 0)
        {
            ConfirmButton.Disabled = true;
            return;
        }

        ConfirmButton.Disabled = false;
    }

    private void ConfirmButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        // the stored amount datafield of the accounts is an int
        if (!int.TryParse(DepositAmount.Text, out var amount) || amount <= 0)
            return;

        AmountDeposited?.Invoke(amount);
        Close();
    }
}

