using Content.Client.UserInterface.Controls;
using Content.Oathlord.Shared.Economy.Systems;
using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class EconomyMachineWindow : FancyWindow
{
    [Dependency] private IEntityManager _entMan = default!;

    private OathlordEconomySystem? _economy;
    private EntityUid? _owner;

    public EconomyMachineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _economy = _entMan.System<OathlordEconomySystem>();
    }

    public void Populate()
    {
        Accounts.Children.Clear();
        if (_economy is null || _owner is not { } owner)
            return;

        if (_economy.GetCurrentEconomy(owner) is not { } mapEconomy)
            return;

        foreach (var account in mapEconomy.Comp.ActiveAccounts)
        {
            var name = Identity.Name(account, _entMan);
            var btn = new Button
            {
                Text = name,
            };
            Accounts.AddChild(btn);
        }
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }
}

