using Content.Oathlord.Shared.Economy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class LoanControl : Control
{
    private LoanData _loan;

    public Action<LoanData>? PayLoanRequest;

    public LoanControl(LoanData loan, float interest)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _loan = loan;

        var interestAmount = (int)(interest * loan.Amount);

        DueTimeLabel.Text = $"Due Time: {loan.DueTime.TotalMinutes} minutes"; // todo: once we get day system, convert to days and "in-game" hours...
        AmountLabel.Text = $"To Pay: {loan.Amount} (+{interestAmount} interest)";
        if (loan.Reason is { } reason)
            ReasonLabel.Text = $"Reason: {reason}";

        PaidLabel.Text = loan.Paid ? "Paid" : "Not Paid";
        PaidLabel.FontColorOverride = loan.Paid ? Color.Green : Color.Red;
        PayLoanButton.Visible = loan.Paid == false;

        PayLoanButton.OnPressed += PayLoanButtonOnOnPressed;
    }

    private void PayLoanButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        PayLoanRequest?.Invoke(_loan);
    }

    public LoanControl()
    {
        RobustXamlLoader.Load(this);
    }
}

