using Content.Oathlord.Shared.Economy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class TransactionHistoryControl : Control
{
    public TransactionHistoryControl(TransactionData transaction)
    {
        RobustXamlLoader.Load(this);

        var loc = Loc.GetString(
            $"economy-transaction-{transaction.Type.ToString().ToLower()}",
            ("amount", transaction.Amount),
            ("target", transaction.Initiator));

        TransactionLabel.Text = loc;
    }

    public TransactionHistoryControl()
    {
        RobustXamlLoader.Load(this);
    }
}

