using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class TransactionHistoryControl : Control
{
    public TransactionHistoryControl(string transaction)
    {
        RobustXamlLoader.Load(this);
        TransactionLabel.Text = transaction;
    }

    public TransactionHistoryControl()
    {
        RobustXamlLoader.Load(this);
    }
}

