using Content.Oathlord.Client.Oaths.UI.Controls;
using Content.Oathlord.Common.Oaths;
using Content.Oathlord.Shared.Oaths;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Oaths.UI;

[GenerateTypedNameReferences]
public sealed partial class OathProfileEditor : BoxContainer
{
    private OathSystem _oath;
    private IPrototypeManager _proto;
    private SpriteSystem _sprite;

    private ProtoId<OathPrototype>? _currentOath;

    /// <summary>
    /// Raised when the user clicks the save button
    /// </summary>
    public event Action<ProtoId<OathPrototype>>? OnSave;

    public OathProfileEditor(IPrototypeManager proto, OathSystem oath, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        _oath = oath;
        _proto = proto;
        _sprite = sprite;

        SaveButton.OnPressed += SaveButtonOnPressed;

        SetupOaths();
    }

    private void SetupOaths()
    {
        OathContainer.Children.Clear();
        foreach (var oath in _oath.AllOaths)
        {
            var oathControl = new OathControl(oath, _proto, _sprite);
            OathContainer.AddChild(oathControl);

            oathControl.OathButton.OnPressed += _ => { _currentOath = oathControl.Oath; };
        }
    }

    private void SaveButtonOnPressed(BaseButton.ButtonEventArgs obj)
    {
        if (_currentOath is not { } currentOath)
            return;

        OnSave?.Invoke(currentOath);
    }
}

