using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Blacksmith.Anvil;

[GenerateTypedNameReferences]
public sealed partial class AnvilRecipe : Control
{
    public AnvilRecipe()
    {
        RobustXamlLoader.Load(this);
    }
}
