using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Oathlord.Shared.Blacksmith.Anvil;
using Content.Shared.Storage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Containers;

namespace Content.Oathlord.Client.Blacksmith.Anvil;

[GenerateTypedNameReferences]
public sealed partial class AnvilWindow : FancyWindow
{
    [Dependency] private IEntityManager _entMan = default!;
    private SharedContainerSystem _container;

    private EntityQuery<AnvilComponent> _anvilQuery;

    private AnvilRecipesWindow? _recipesWindow;

    private EntityUid _owner;

    public AnvilWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _container = _entMan.System<SharedContainerSystem>();

        _anvilQuery = _entMan.GetEntityQuery<AnvilComponent>();

        OutputsButton.OnPressed += OutputsButtonOnOnPressed;
    }

    private void OutputsButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        if (!_container.TryGetContainer(_owner, StorageComponent.ContainerId, out var container))
            return;

        _recipesWindow?.Close();
        _recipesWindow = new AnvilRecipesWindow();
        _recipesWindow.SetupWindow(container.ContainedEntities);
        _recipesWindow.OnClose += () => _recipesWindow = null;

        _recipesWindow.OpenCentered();
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }

    public void UpdateWindow()
    {
        if (!_anvilQuery.TryComp(_owner, out var anvilComponent) || !_container.TryGetContainer(_owner, StorageComponent.ContainerId, out var container))
            return;

        UpdateViewsContainer(container.ContainedEntities, anvilComponent.AllowedWorkables);
    }

    private void UpdateViewsContainer(IReadOnlyList<EntityUid> entities, int amount)
    {
        ViewsContainer.Children.Clear();
        for (var i = 0; i < amount; i++)
        {
            var metalView = new WorkableMetalView();
            var element = entities.ElementAtOrDefault(i);
            metalView.SetupView(element);

            ViewsContainer.AddChild(metalView);
        }
    }
}

