using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Oathlord.Shared.Blacksmith.Anvil;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Blacksmith.Anvil;

[GenerateTypedNameReferences]
public sealed partial class AnvilRecipesWindow : FancyWindow
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;
    private AnvilSystem _anvil;

    public AnvilRecipesWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _anvil = _entMan.System<AnvilSystem>();
    }

    public void SetupWindow(IReadOnlyList<EntityUid> metals)
    {
        RecipesContainer.Children.Clear();

        var metalList = metals.ToList();
        var recipes = _anvil.GetRecipes(metalList);
        foreach (var recipe in recipes)
        {
            // we already resolved while getting the recipes
            if (!_protoMan.TryIndex(recipe, out var recipeProto))
                continue;

            var anvilRecipe = new AnvilRecipe();
            anvilRecipe.SetTexture(recipeProto.Result);

            RecipesContainer.AddChild(anvilRecipe);
        }
    }
}

