using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Blacksmith.Anvil;

/// <summary>
/// A pre-set control for anvil recipes
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AnvilRecipe : Control
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _proto = default!;
    private SpriteSystem _sprite;

    public AnvilRecipe()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entMan.System<SpriteSystem>();
    }

    public void SetTexture(EntProtoId result)
    {
        if (_proto.TryIndex(result, out var entityProto))
            RecipeButton.TextureNormal = _sprite.Frame0(entityProto);
    }
}
