using Content.Client.UserInterface.Controls;
using Content.Oathlord.Shared.Blacksmith.Anvil.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Blacksmith.Anvil;

[GenerateTypedNameReferences]
public sealed partial class AnvilRecipesWindow : FancyWindow
{
    public AnvilRecipesWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetupWindow(List<ProtoId<AnvilRecipePrototype>> recipes)
    {

    }
}

