using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Oathlord.Shared.Blacksmith.Anvil;
using Content.Oathlord.Shared.Blacksmith.Anvil.Prototypes;
using Content.Shared.Storage;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Containers;

namespace Content.Oathlord.Client.Blacksmith.Anvil;

[GenerateTypedNameReferences]
public sealed partial class AnvilWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private IEntityManager _entMan = default!;
    private SharedContainerSystem _container;
    private SpriteSystem _sprite;

    private EntityQuery<AnvilComponent> _anvilQuery;

    private AnvilRecipesWindow? _recipesWindow;

    public Action<ProtoId<AnvilRecipePrototype>>? RecipeSelected;

    private EntityUid _owner;

    public AnvilWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _container = _entMan.System<SharedContainerSystem>();
        _sprite = _entMan.System<SpriteSystem>();
        _anvilQuery = _entMan.GetEntityQuery<AnvilComponent>();

        OutputsButton.OnPressed += OutputsButtonOnOnPressed;
    }

    private void OutputsButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        if (!_container.TryGetContainer(_owner, StorageComponent.ContainerId, out var container) || container.ContainedEntities.Count == 0)
            return;

        _recipesWindow?.Close();
        _recipesWindow = new AnvilRecipesWindow();
        _recipesWindow.SetupWindow(container.ContainedEntities);
        _recipesWindow.RecipeSelected += args => RecipeSelected?.Invoke(args);
        _recipesWindow.OnClose += () => _recipesWindow = null;

        _recipesWindow.OpenCentered();
    }

    public override void Close()
    {
        base.Close();
        _recipesWindow?.Close();
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }

    public void UpdateWindow()
    {
        if (!_anvilQuery.TryComp(_owner, out var anvilComponent) || !_container.TryGetContainer(_owner, StorageComponent.ContainerId, out var container))
            return;

        UpdateViewsContainer(container.ContainedEntities, anvilComponent.AllowedWorkables);
        UpdateRecipe(anvilComponent.SelectedRecipe);
    }

    private void UpdateViewsContainer(IReadOnlyList<EntityUid> entities, int amount)
    {
        ViewsContainer.Children.Clear();
        for (var i = 0; i < amount; i++)
        {
            var metalView = new WorkableMetalView();
            var element = entities.ElementAtOrDefault(i);
            metalView.SetupView(element);

            ViewsContainer.AddChild(metalView);
        }
    }

    private void UpdateRecipe(ProtoId<AnvilRecipePrototype>? recipe)
    {
        if (recipe is not { } anvilRecipe|| !_proto.TryIndex(anvilRecipe, out var recipeProto))
        {
            RecipeName.Text = "No recipe has been selected... Click 'Outputs' to select one!";
            WorkRequired.Text = string.Empty;
            RecipeView.Visible = false;
            RecipeView.Texture = null;
            return;
        }

        if (!_proto.TryIndex(recipeProto.Result, out var entityProto))
            return;

        RecipeName.Text = entityProto.Name;
        WorkRequired.Text = $"Work Required: {recipeProto.WorkRequired.ToString()}";

        RecipeView.Texture = _sprite.Frame0(entityProto);
        RecipeView.Visible = true;
    }
}

