using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Blacksmith.Anvil;

[GenerateTypedNameReferences]
public sealed partial class AnvilWindow : FancyWindow
{
    public AnvilWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

