using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Blacksmith.Anvil;

[GenerateTypedNameReferences]
public sealed partial class AnvilPattern : Control
{
    public AnvilPattern()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetLabel(int num)
    {
        PatternLabel.Text = num.ToString();
    }

    public void SetComplete()
    {
        PatternPanelContainer.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#36454F"),
            BorderColor = Color.FromHex("#008000"),
            BorderThickness = new Thickness(2),
        };
    }
}
