using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Blacksmith.Anvil;

[GenerateTypedNameReferences]
public sealed partial class RecipeHitButton : Button
{
    private int _hitNumber;

    public RecipeHitButton()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetHitNumber(int hitNumber)
    {
        _hitNumber = hitNumber;
        Text = hitNumber > 0 ? $"+{hitNumber}" : $"{hitNumber}";
    }
}

