using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Blacksmith.Anvil;

[GenerateTypedNameReferences]
public sealed partial class WorkableMetalView : Control
{
    public WorkableMetalView()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetupView(EntityUid? entity)
    {
        MetalView.SetEntity(entity);
    }
}

