using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Blacksmith.Anvil;

/// <summary>
/// A pre-set control for displaying workable metals.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WorkableMetalView : Control
{
    public WorkableMetalView()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetupView(EntityUid? entity)
    {
        MetalView.SetEntity(entity);
    }

    public void SetupView(NetEntity netEnt)
    {
        MetalView.SetEntity(netEnt);
    }
}

