using Content.Shared.Actions.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.UserInterface.Systems.Spells.Widgets;

[GenerateTypedNameReferences]
public sealed partial class SpellsButton : UIWidget
{
    [Dependency] private IEntityManager _entMan = default!;
    private SpriteSystem _sprite;

    public SpellsButton()
    {
        RobustXamlLoader.Load(this);

        _sprite = _entMan.System<SpriteSystem>();
    }

    public void UpdateSpellWidget(EntityUid? spell)
    {
        if (spell == null)
        {
            OpenSpellsButton.TextureNormal = null;
            return;
        }

        // idc now for an EQ, we will use sprite system once stable
        if (!_entMan.TryGetComponent<ActionComponent>(spell, out var actionComp) || actionComp.Icon is not { } icon)
            return;

        var tex = _sprite.Frame0(icon);
        OpenSpellsButton.TextureNormal = tex;
    }
}
