using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.UserInterface.Systems.Spells.Widgets;

[GenerateTypedNameReferences]
public sealed partial class SpellsButton : UIWidget
{
    public SpellsButton()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateSpellWidget(EntityUid? spell)
    {
        if (spell is not { } spellEntity)
        {
            SelectedSpellSlot.RemoveSpell();
            return;
        }

        SelectedSpellSlot.AddSpell(spellEntity);
    }
}
