using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.UserInterface.Systems.Spells.Windows;

[GenerateTypedNameReferences]
public sealed partial class SpellsWindow : FancyWindow
{
    public SpellsWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
