using Content.Client.Actions.UI;
using Content.Client.Cooldown;
using Content.Client.UserInterface;
using Content.Shared.Actions.Components;
using Content.Shared.Examine;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics.RSI;
using Robust.Shared.Timing;

namespace Content.Oathlord.Client.UserInterface.Systems.Spells.Controls;

[GenerateTypedNameReferences]
public sealed partial class SpellSlot : Control, IEntityControl
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPlayerManager _player = default!;

    private EntityQuery<SpriteComponent> _spriteQuery;
    private EntityQuery<ActionComponent> _actionQuery;

    /// <summary>
    /// The spell that is owned by this slot
    /// </summary>
    public EntityUid? Spell;

    /// <summary>
    /// Is the spell in the active category?
    /// </summary>
    public bool Active;

    /// <summary>
    /// Spell entity with action component so we don't get it every frame
    /// </summary>
    private Entity<ActionComponent>? _actionEntity;

    private CooldownGraphic _cooldown;

    public SpellSlot()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SpellTexButton.TooltipSupplier = SetupTooltip;

        _cooldown = new CooldownGraphic {Visible = false};
        SpellPanel.AddChild(_cooldown);

        _spriteQuery = _entMan.GetEntityQuery<SpriteComponent>();
        _actionQuery = _entMan.GetEntityQuery<ActionComponent>();
    }

    public void AddSpell(EntityUid spell)
    {
        if (!_spriteQuery.TryComp(spell, out var sprite) || !_actionQuery.TryComp(spell, out var action))
            return;

        SpellTexButton.TextureNormal = sprite.Icon?.GetFrame(RsiDirection.South, 0);
        Spell = spell;

        _actionEntity = (spell, action);
    }

    public void RemoveSpell()
    {
        Spell = null;
        SpellTexButton.TextureNormal = null;
        _actionEntity = null;
        _cooldown.Visible = false;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _cooldown.Visible = _actionEntity?.Comp.Cooldown != null;
        if (_actionEntity?.Comp is not { } action)
            return;

        if (action.Cooldown is { } cooldown)
            _cooldown.FromTime(cooldown.Start, cooldown.End);
    }

    private Control? SetupTooltip(Control sender)
    {
        if (Spell is not { } spellEntity || !_entMan.TryGetComponent(spellEntity, out MetaDataComponent? metadata))
            return null;

        // todo:
        // expand this with extra fluff about spell types etc
        // in the future, we should have our own tooltip control for spells

        var msg = FormattedMessage.FromMarkupPermissive(metadata.EntityName);
        var desc = FormattedMessage.FromMarkupPermissive(metadata.EntityDescription);

        if (_player.LocalEntity is not { } player)
            return null;

        var ev = new ExaminedEvent(desc, spellEntity, player, true, !desc.IsEmpty);
        _entMan.EventBus.RaiseLocalEvent(spellEntity, ev);

        var newDesc = ev.GetTotalMessage();

        return new ActionAlertTooltip(msg, newDesc);
    }

    public EntityUid? UiEntity => Spell;
}

