using Content.Client.Actions.UI;
using Content.Client.Cooldown;
using Content.Shared.Actions.Components;
using Content.Shared.Examine;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Oathlord.Client.UserInterface.Systems.Spells.Controls;

[GenerateTypedNameReferences]
public sealed partial class SpellSlot : Control
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPlayerManager _player = default!;

    private SpriteSystem _sprite;

    /// <summary>
    /// The spell that is owned by this slot
    /// </summary>
    public EntityUid? Spell;

    public bool Active;

    /// <summary>
    /// Spell entity with action component so we don't get it every frame
    /// </summary>
    private Entity<ActionComponent>? _actionEntity;

    public CooldownGraphic Cooldown;

    public SpellSlot()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SpellTexButton.TooltipSupplier = SetupTooltip;

        Cooldown = new CooldownGraphic {Visible = false};
        SpellPanel.AddChild(Cooldown);

        _sprite = _entMan.System<SpriteSystem>();
    }

    public void AddSpell(EntityUid spell, bool active)
    {
        // todo: rework this for sprite actions once stable
        if (!_entMan.TryGetComponent(spell, out ActionComponent? action) || action.Icon is not { } iconSpecifier)
            return;

        SpellTexButton.TextureNormal = _sprite.Frame0(iconSpecifier);
        Spell = spell;
        Active = active;

        _actionEntity = (spell, action);
    }

    public void AddSpell(EntityUid spell)
    {
        // todo: rework this for sprite actions once stable
        if (!_entMan.TryGetComponent(spell, out ActionComponent? action) || action.Icon is not { } iconSpecifier)
            return;

        SpellTexButton.TextureNormal = _sprite.Frame0(iconSpecifier);
        Spell = spell;

        _actionEntity = (spell, action);
    }

    public void RemoveSpell()
    {
        Spell = null;
        SpellTexButton.TextureNormal = null;
        _actionEntity = null;
        Cooldown.Visible = false;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        Cooldown.Visible = _actionEntity?.Comp.Cooldown != null;
        if (_actionEntity?.Comp is not { } action)
            return;

        if (action.Cooldown is { } cooldown)
            Cooldown.FromTime(cooldown.Start, cooldown.End);
    }

    private Control? SetupTooltip(Control sender)
    {
        if (Spell is not { } spellEntity || !_entMan.TryGetComponent(spellEntity, out MetaDataComponent? metadata))
            return null;

        // todo: expand this with extra fluff about spell types etc

        var msg = FormattedMessage.FromMarkupPermissive(metadata.EntityName);
        var desc = FormattedMessage.FromMarkupPermissive(metadata.EntityDescription);

        if (_player.LocalEntity is not { } player)
            return null;

        var ev = new ExaminedEvent(desc, spellEntity, player, true, !desc.IsEmpty);
        _entMan.EventBus.RaiseLocalEvent(spellEntity, ev);

        var newDesc = ev.GetTotalMessage();

        return new ActionAlertTooltip(msg, newDesc);
    }
}

