using Content.Shared.Actions.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.UserInterface.Systems.Spells.Controls;

[GenerateTypedNameReferences]
public sealed partial class SpellSlot : Control
{
    [Dependency] private IEntityManager _entMan = default!;

    private SpriteSystem _sprite;

    /// <summary>
    /// The spell that is owned by this slot
    /// </summary>
    public EntityUid? Spell;

    public bool Active;

    public SpellSlot()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entMan.System<SpriteSystem>();
    }

    public void AddSpell(EntityUid spell, bool active)
    {
        // todo: rework this for sprite actions once stable
        if (!_entMan.TryGetComponent(spell, out ActionComponent? action) || action.Icon is not { } iconSpecifier)
            return;

        SpellTexButton.TextureNormal = _sprite.Frame0(iconSpecifier);
        Spell = spell;
        Active = active;
    }

    public void AddSpell(EntityUid spell)
    {
        // todo: rework this for sprite actions once stable
        if (!_entMan.TryGetComponent(spell, out ActionComponent? action) || action.Icon is not { } iconSpecifier)
            return;

        SpellTexButton.TextureNormal = _sprite.Frame0(iconSpecifier);
        SpellTexButton.ToolTip = spell.Id.ToString();
        Spell = spell;
    }

    public void RemoveSpell()
    {
        Spell = null;
        SpellTexButton.TextureNormal = null;
        SpellTexButton.ToolTip = null;
    }
}

