using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Oaths.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class OathTooltip : PanelContainer
{
    public OathTooltip(string name, string description)
    {
        RobustXamlLoader.Load(this);

        OathNameLabel.Text = name;
        OathDescLabel.Text = description;
    }
}

