using Content.Oathlord.Common.Oaths;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Oaths.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class OathControl : Control
{
    private IPrototypeManager _proto;
    private SpriteSystem _sprite;

    public ProtoId<OathPrototype> Oath;

    public OathControl(ProtoId<OathPrototype> oath, IPrototypeManager proto, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);
        _proto = proto;
        _sprite = sprite;

        UpdateOath(oath);
    }

    /// <summary>
    /// Sets the oath, and updates the icon on the UI
    /// </summary>
    /// <param name="oath">The updated oath</param>
    public void UpdateOath(ProtoId<OathPrototype> oath)
    {
        Oath = oath;
        if (!_proto.TryIndex(oath, out var oathProto))
            return;

        // todo: we need a dedicated tooltip supplier...
        OathButton.Tooltip = $"{oathProto.Name}: {oathProto.Description}";

        if (oathProto.Background is { } background && OathPanel.PanelOverride is StyleBoxTexture styleBox)
            styleBox.Texture = _sprite.Frame0(background);

        if (oathProto.Icon is { } icon)
            OathButton.TextureNormal = _sprite.Frame0(icon);
    }
}

