using Content.Oathlord.Common.Oaths;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Oaths.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class OathControl : Control
{
    private IPrototypeManager _proto;
    private SpriteSystem _sprite;

    public ProtoId<OathPrototype> Oath;

    public OathControl(ProtoId<OathPrototype> oath, IPrototypeManager proto, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);
        _proto = proto;
        _sprite = sprite;

        UpdateOath(oath);

        OathButton.TooltipSupplier = SupplyTooltip;
    }

    private Control? SupplyTooltip(Control sender)
    {
        if (!_proto.TryIndex(Oath, out var oath))
            return null;

        var name = oath.Name;
        var desc = oath.Description;

        return new OathTooltip(name, desc);
    }

    /// <summary>
    /// Sets the oath, and updates the icon on the UI
    /// </summary>
    /// <param name="oath">The updated oath</param>
    public void UpdateOath(ProtoId<OathPrototype> oath)
    {
        Oath = oath;
        if (!_proto.TryIndex(oath, out var oathProto))
            return;

        if (OathPanel.PanelOverride is StyleBoxTexture styleBox)
        {
            var bg = oathProto.Background;
            styleBox.Texture = bg == null ? null : _sprite.Frame0(bg);
        }

        var icon = oathProto.Icon;
        OathButton.TextureNormal = icon == null ? null : _sprite.Frame0(icon);
    }
}

