- type: entity
  id: BaseExpedition
  categories: [ HideSpawnMenu ]
  parent:
  - BaseStation
  - BaseStationAllEventsEligible
  - BaseStationJobsSpawning
  - BaseStationAlertLevels
  - BaseStationRecords
  - BaseEconomy

# Sets up a basic economy
- type: entity
  abstract: true
  id: BaseEconomy
  components:
  - type: EconomyMap
