- type: entity
  id: BaseExpedition
  categories: [ HideSpawnMenu ]
  parent:
  - BaseStation
  - BaseStationAllEventsEligible
  - BaseStationJobsSpawning
  - BaseStationAlertLevels
  - BaseStationRecords
