using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.UserInterface.Systems.Mana.Widgets;

[GenerateTypedNameReferences]
public sealed partial class ManaBar : UIWidget
{
    public ManaBar()
    {
        RobustXamlLoader.Load(this);
    }

    public void SyncMana(FixedPoint2 mana, FixedPoint2 maxMana, bool canUse)
    {
        if (ManaProgress.ForegroundStyleBoxOverride is StyleBoxFlat flat)
        {
            flat.BackgroundColor = canUse ?  Color.FromHex("#28b4d2") : Color.Gray;
        }

        ManaProgress.MaxValue = (float)maxMana;
        ManaProgress.Value = (float)mana;
    }
}

