using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.UserInterface.Systems.Mana.Widgets;

[GenerateTypedNameReferences]
public sealed partial class ManaBar : UIWidget
{
    public ManaBar()
    {
        RobustXamlLoader.Load(this);
    }

    public void SyncMana(FixedPoint2 mana)
    {
        ManaProgress.Value = (float)mana;
        Log.Info($"Mana: {mana}");
    }
}

