using Content.Client.Resources;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.UserInterface.Systems.Mana.Widgets;

[GenerateTypedNameReferences]
public sealed partial class ManaBar : UIWidget
{
    [Dependency] private IResourceCache _res = default!;

    public ManaBar()
    {
        RobustXamlLoader.Load(this);

        var bgTex = _res.GetTexture("/Textures/_Oathlord/Interface/Mana/mana_bar_bg.png");
        var barTex = _res.GetTexture("/Textures/_Oathlord/Interface/Mana/mana_bar_fg.png");

        ManaProgress.BackgroundStyleBoxOverride = new StyleBoxTexture
        {
            Texture = bgTex,
        };
        ManaProgress.ForegroundStyleBoxOverride = new StyleBoxTexture
        {
            Texture = barTex,
        };
    }

    public void SyncMana(FixedPoint2 mana, FixedPoint2 maxMana)
    {
        ManaProgress.MaxValue = (float)maxMana;
        ManaProgress.Value = (float)mana;
    }
}

