using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Range = Robust.Client.UserInterface.Controls.Range;

namespace Content.Oathlord.Client.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class BoxRange : Range
{
    private StyleBox? _styleBoxOverride;

    private bool _vertical;

    public bool Vertical
    {
        get => _vertical;
        set
        {
            if (_vertical != value)
            {
                _vertical = value;
                InvalidateMeasure();
            }
        }
    }

    public StyleBox? StyleBoxOverride
    {
        get => _styleBoxOverride;
        set
        {
            _styleBoxOverride = value;
            InvalidateMeasure();
        }
    }

    public BoxRange()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        var box = _styleBoxOverride;
        if (box == null)
            return;

        if (_vertical)
        {
            var size = PixelHeight * GetAsRatio() + 1; // we need + 1 so it shows up in the UI, as GetRatio can be 0
            if (size > 0)
            {
                box.Draw(handle, UIBox2.FromDimensions(0, PixelHeight - size, PixelWidth, PixelHeight), UIScale);
            }
        }
        else
        {
            var minSize = box.MinimumSize;
            var size = PixelWidth * GetAsRatio() - minSize.X;
            if (size > 0)
            {
                box.Draw(handle, UIBox2.FromDimensions(minSize.X + size, 0, PixelWidth, PixelHeight), UIScale);
            }
        }
    }

    protected override Vector2 MeasureOverride(Vector2 availableSize)
    {
        var size = _styleBoxOverride?.MinimumSize ?? Vector2.Zero;
        return size;
    }
}

