using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.UserInterface.Controls;

/// <summary>
/// Progress bar that has a label providing it's current value inside of it.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LabelProgressBar : ProgressBar
{
    public LabelProgressBar()
    {
        RobustXamlLoader.Load(this);

        ValueLabel.Text = Value.ToString("N0");
        OnValueChanged += OnOnValueChanged;
    }

    private void OnOnValueChanged(Robust.Client.UserInterface.Controls.Range obj)
    {
        ValueLabel.Text = Value.ToString("N0");
    }
}

